---
title: "AoL Mulvar"
output:
  word_document: default
  html_notebook: default
---

# Library

```{r}
library(car)
library(expm)
library(MVN)
library(MASS)
library(caret)
```

# Dataset

```{r}
# Baca dataset
df = read.csv(file.choose(), sep = ",", header = TRUE)
df
```

# Cek Asumsi Normalitas

```{r}
result_mardia <- mvn(data = df, mvnTest = "hz")
print(result_mardia)
```

```{r}
# Transformasi data menggunakan log
data_trans = log(df) 
result_mardia <- mvn(data = data_trans, mvnTest = "hz")
#print(result_mardia) # Tidak lulus

# Transformasi data menggunakan square root
data_trans2 = sqrt(df)
result_mardia <- mvn(data = data_trans2, mvnTest = "hz")
#print(result_mardia) # Tidak lulus

# Transformasi menggunakan rumus resiprokal (Reciprocal)
data_trans3 = 1 / (df + 1)
result_mardia <- mvn(data = data_trans3, mvnTest = "hz")
#print(result_mardia) # Tidak lulus

# Transformasi menggunakan metode Box-cox
boxcox_transform <- preProcess(df, method = "BoxCox")
data_trans4 <- predict(boxcox_transform, df)
result_mardia <- mvn(data = data_trans4, mvnTest = "hz")
print(result_mardia) # Lulus
```

# Cek Asumsi Multikolinearitas

```{r}
# Uji Multikolineritas
# Vif untuk X1
vif_x1 = vif(lm(X1 ~ X2+X3, data=data_trans4[1:3]))
vif_x1

# Vif untuk X2
vif_x2 = vif(lm(X2 ~ X1+X3, data=data_trans4[1:3]))
vif_x2

# Vif untuk X3
vif_x1 = vif(lm(X3 ~ X1+X2, data=data_trans4[1:3]))
vif_x1

# Vif untuk Y1
vif_y1 = vif(lm(Y1 ~ Y2+Y3, data=data_trans4[4:6]))
vif_y1

# Vif untuk Y2
vif_y2 = vif(lm(Y2 ~ Y1+Y3, data=data_trans4[4:6]))
vif_y2

# Vif untuk Y3
vif_y3 = vif(lm(Y3 ~ Y1+Y2, data=data_trans4[4:6]))
vif_y3
```

# Cek Asumsi Linearitas

```{r}
# Menghitung matriks korelasi 
cor_matrix = cor(data_trans4, method='pearson')
cor_matrix
```

# Canonical Correlation Analysis

```{r}
# Mencari determinan dari matriks
det_R = det(cor_matrix)

# Membagi matriks korelasi menjadi submatriks untuk variabel X dan Y
rho11 = cor_matrix[1:3,1:3]
rho12 = cor_matrix[1:3,4:6]
rho21 = cor_matrix[4:6,1:3]
rho22 = cor_matrix[4:6,4:6]

# Menghitung determinan dari submatriks rho11 dan rho22
det_rho11 = det(rho11)
det_rho22 = det(rho22)

# Menghitung invers dari akar matriks rho11
rho11_sqrtm_inverse = solve(sqrtm(rho11))

# Menghitung invers dari matriks rho22
rho22_inverse = solve(rho22)

# Menghitung matriks transformasi A
A = rho11_sqrtm_inverse%*%rho12%*%rho22_inverse%*%rho21%*%rho11_sqrtm_inverse

# Menghitung nilai eigen dan vektor eigen dari matriks A
eigen(A)
```

```{r}
# Korelasi kanonik adalah akar dari nilai eigen
f_cor_can1 = sqrt(eigen(A)$values[1])
f_cor_can2 = sqrt(eigen(A)$values[2])
f_cor_can3 = sqrt(eigen(A)$values[3])

can_cor <- c(f_cor_can1, f_cor_can2, f_cor_can3)
print(can_cor)

# Korelasi Kanonik Kuadrat
can_cor_squared <- can_cor^2
print(can_cor_squared)
```

```{r}
# Ekstraksi vektor eigen untuk kombinasi linear variabel X
e1 = eigen(A)$vectors[1:3, 1]
e2 = eigen(A)$vectors[1:3, 2]
e3 = eigen(A)$vectors[1:3, 3]

# Menghitung invers dari akar matriks rho22
rho22_sqrtm_inverse = solve(sqrtm(rho22))
rho11_inverse = solve(rho11)

# Ekstraksi vektor eigen untuk kombinasi linear variabel Y
f1 = eigen(rho22_sqrtm_inverse%*%rho21%*%rho11_inverse%*%rho12%*%rho22_sqrtm_inverse)$vectors[1:3, 1]
f2 = eigen(rho22_sqrtm_inverse%*%rho21%*%rho11_inverse%*%rho12%*%rho22_sqrtm_inverse)$vectors[1:3, 2]
f3 = eigen(rho22_sqrtm_inverse%*%rho21%*%rho11_inverse%*%rho12%*%rho22_sqrtm_inverse)$vectors[1:3, 3]

# Membentuk kombinasi linear variabel X berdasarkan vektor eigen
a11 = e1%*%rho11_sqrtm_inverse
a21 = e2%*%rho11_sqrtm_inverse
a31 = e3%*%rho11_sqrtm_inverse

# Membentuk kombinasi linear variabel Y berdasarkan vektor eigen
b11 = f1%*%rho22_sqrtm_inverse
b21 = f2%*%rho22_sqrtm_inverse
b31 = f3%*%rho22_sqrtm_inverse

a11 
a21 
a31
b11 
b21 
b31 

# Kombinasi linear

# U1 = -0.03813304X1 -0.2411984X2 -0.8417242X3
# U2 = 0.9900841X1 - 0.6811253X2 + 0.02011261X3
# U3 = -0.478448 X1 - 0.9191664X2 + 0.8482445X3

# V1 = 0.1061481Y1 - 0.1912168Y2 - 0.8935174Y3
# V2 = 0.3690851Y1 - 1.127967Y2 + 0.6976609Y3
# V3 = 0.9559397Y1 + 0.160577Y2 + 0.00355592Y3
```

```{r}
# Bobot Kanonikal
U1 <- as.matrix(data_trans4[,1:3]) %*% t(a11)
U2 <- as.matrix(data_trans4[,1:3]) %*% t(a21)
U3 <- as.matrix(data_trans4[,1:3]) %*% t(a31)

V1 <- as.matrix(data_trans4[,4:6]) %*% t(b11)
V2 <- as.matrix(data_trans4[,4:6]) %*% t(b21)
V3 <- as.matrix(data_trans4[,4:6]) %*% t(b31)

U1.load <- cor(data_trans4[,1:3], U1)
U2.load <- cor(data_trans4[,1:3], U2)
U3.load <- cor(data_trans4[,1:3], U3)

V1.load <- cor(data_trans4[,4:6], V1)
V2.load <- cor(data_trans4[,4:6], V2)
V3.load <- cor(data_trans4[,4:6], V3)

t(U1.load)
t(U2.load)
t(U3.load)

t(V1.load)
t(V2.load)
t(V3.load)
```

# Uji Serentak

```{r}
# Menghitung Wilk's Lambda
Lambda_wilk = det_R/(det_rho11*det_rho22)

# Membandingkan lambda dengan nilai kritis
# Rumusnya lambda p = 3, q = 3, 
Lambda_alpha_3_3_30=0.483


if (Lambda_wilk < Lambda_alpha_3_3_30) {
  print("Tolak H0: Ada korelasi signifikan antara kelompok X dan Y.")
} else {
  print("Gagal menolak H0: Tidak ada korelasi signifikan antara kelompok X dan Y.")
}
```

# Uji Parsial

```{r}
Lambda_1 = (1-(f_cor_can1^2))*(1-(f_cor_can2^2))*(1-(f_cor_can3^2))
Lambda_2 = (1-(f_cor_can2^2))*(1-(f_cor_can3^2))
Lambda_3 = (1-(f_cor_can3^2))

Lambda <- c(Lambda_1, Lambda_2, Lambda_3)

canonicalPartialTest <- function(p, q) {
  for (k in 1:p) {
    print(paste0("lambda_", k))
    print("===================")
    
    P <- p-k+1
    vH <- q-k+1
    vE <- nrow(data_trans4)-k-q
    
    w = nrow(data_trans4)-(1/2)*(p+q+3)
    t = sqrt(
      ((P)^2*(vH)^2-4)/
        ((P)^2+(vH)^2-5)
    )
    print(paste0("w: ", w))
    print(paste0("t: ", t))
    # t = sqrt(((p-k+1)^2*(q-k+1)^2-4)/((p-k+1)^2+(q-k+1)^2-5))
    
    df1 <- round((P) * (vH))
    df2 <- round(w*t-(1/2)*(df1)+1)
    
    print(paste0("df1: ", df1))
    print(paste0("df2: ", t))
    
    F.test<- ((1-Lambda[k]^(1/t))/(Lambda[k]^(1/t))) * (df2/df1)
    print(paste0("F test: ", F.test))
    
    F.crit <- qf(1-0.01, df1, df2)
    print(paste0("F crit: ", F.crit))
    
    if (F.test > F.crit) {
      print("reject H0")
    }
    else {
      print("failed to reject H0")
    }
    print("===================")
  }
}

canonicalPartialTest(3, 3)
```